### Create Oglas
POST http://localhost:8080/oglasi
Content-Type: application/json

{
  "name":"A oglas",
  "userId": 1,
  "description":"sdgffd.",
  "dueDate":[2020,3,26,20,24],
  "city":"Gostivar",
  "isActive": true,
  "price": 200.0,
  "id": 0
}

### Get All Oglasi
GET http://localhost:8080/oglasi?pageNo=0&pageSize=10

### Get Oglas by ID
GET http://localhost:8080/oglasi/3

### Get All Oglasi By User Id
GET http://localhost:8080/oglasi/user/2?pageNo=0&pageSize=10

### Modify Oglas ID
PUT http://localhost:8080/oglasi/5
Content-Type: application/json

{
  "name":"Krecenje na soba 2 so 5 m2",
  "userId": 2,
  "description":"agon kawi",
  "dueDate": [2020,3,26,20,24],
  "city":"Skopje",
  "isActive":false,
  "price": 10.50
}

### Set Oglas ID with deal
POST http://localhost:8080/oglasi/dogovor
Content-Type: application/x-www-form-urlencoded

oglasId=4&madeById=2

### Delete Oglas ID
DELETE http://localhost:8080/oglasi/3

###

